# Generated by Django 4.2.6 on 2023-12-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiseonly', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='phn',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
